language: java

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew build
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t robertreynisson/accountmanagement .
  - docker push robertreynisson/accountmanagement