GET http://{{host}}/account/
Accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.log(response.body)
%}
###

POST http://{{host}}/account/
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "password": "robert123",
  "userName": "robertreynisson",
  "firstname": "robert",
  "lastname": "reynisson",
  "role": "ADMIN"
}

> {%
    client.log(response.body)
%}

###